# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stdmetadata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stdmetadata.proto',
  package='stdmetadatapb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11stdmetadata.proto\x12\rstdmetadatapb\"E\n\nStdRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontract_id\x18\x03 \x01(\x03\"q\n\x13StdMetadataResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1c\n\x14position_category_id\x18\x02 \x01(\x03\x12\x0e\n\x06locale\x18\x03 \x01(\t\x12\x1c\n\x14\x63ontract_duration_id\x18\x04 \x01(\x03\x32`\n\x0bStdMetadata\x12Q\n\x0eGetStdMetadata\x12\x19.stdmetadatapb.StdRequest\x1a\".stdmetadatapb.StdMetadataResponse\"\x00\x62\x06proto3')
)




_STDREQUEST = _descriptor.Descriptor(
  name='StdRequest',
  full_name='stdmetadatapb.StdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='stdmetadatapb.StdRequest.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='stdmetadatapb.StdRequest.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract_id', full_name='stdmetadatapb.StdRequest.contract_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=105,
)


_STDMETADATARESPONSE = _descriptor.Descriptor(
  name='StdMetadataResponse',
  full_name='stdmetadatapb.StdMetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='stdmetadatapb.StdMetadataResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position_category_id', full_name='stdmetadatapb.StdMetadataResponse.position_category_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locale', full_name='stdmetadatapb.StdMetadataResponse.locale', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contract_duration_id', full_name='stdmetadatapb.StdMetadataResponse.contract_duration_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=220,
)

DESCRIPTOR.message_types_by_name['StdRequest'] = _STDREQUEST
DESCRIPTOR.message_types_by_name['StdMetadataResponse'] = _STDMETADATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StdRequest = _reflection.GeneratedProtocolMessageType('StdRequest', (_message.Message,), dict(
  DESCRIPTOR = _STDREQUEST,
  __module__ = 'stdmetadata_pb2'
  # @@protoc_insertion_point(class_scope:stdmetadatapb.StdRequest)
  ))
_sym_db.RegisterMessage(StdRequest)

StdMetadataResponse = _reflection.GeneratedProtocolMessageType('StdMetadataResponse', (_message.Message,), dict(
  DESCRIPTOR = _STDMETADATARESPONSE,
  __module__ = 'stdmetadata_pb2'
  # @@protoc_insertion_point(class_scope:stdmetadatapb.StdMetadataResponse)
  ))
_sym_db.RegisterMessage(StdMetadataResponse)



_STDMETADATA = _descriptor.ServiceDescriptor(
  name='StdMetadata',
  full_name='stdmetadatapb.StdMetadata',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=222,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStdMetadata',
    full_name='stdmetadatapb.StdMetadata.GetStdMetadata',
    index=0,
    containing_service=None,
    input_type=_STDREQUEST,
    output_type=_STDMETADATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STDMETADATA)

DESCRIPTOR.services_by_name['StdMetadata'] = _STDMETADATA

# @@protoc_insertion_point(module_scope)
