# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stdmetadata_pb2 as stdmetadata__pb2


class StdMetadataStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStdMetadata = channel.unary_unary(
        '/stdmetadatapb.StdMetadata/GetStdMetadata',
        request_serializer=stdmetadata__pb2.StdRequest.SerializeToString,
        response_deserializer=stdmetadata__pb2.StdMetadataResponse.FromString,
        )


class StdMetadataServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStdMetadata(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StdMetadataServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStdMetadata': grpc.unary_unary_rpc_method_handler(
          servicer.GetStdMetadata,
          request_deserializer=stdmetadata__pb2.StdRequest.FromString,
          response_serializer=stdmetadata__pb2.StdMetadataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'stdmetadatapb.StdMetadata', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
